sudo: required

language: python

env:
  global:
    - IMAGE_NAME=eloo/raspberrypi3-homeassistant-git 
    - VERSION=`head -n 1 Dockerfile | awk -F ":" '{print $NF}'`
  
services:
  - docker

before_install:
  - echo Build HA version: $VERSION
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t "${IMAGE_NAME}" .

script:
  - docker run -d eloo/raspberrypi3-homeassistant-git /bin/sh -c "hass --version"
  - docker run -d eloo/raspberrypi3-homeassistant-git /bin/sh -c "git --version"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${VERSION}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${VERSION}"
  on:
    branch: master
