sudo: required

language: python

env:
  - IMAGE_NAME=eloo/raspberrypi3-homeassistant-git
  - DOCKER_USERNAME=username
  - DOCKER_PASSWORD=password
  
services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t "${IMAGE_NAME}" .

script:
  - docker run -d eloo/raspberrypi3-homeassistant-git /bin/sh -c "hass --version"

#before_deploy:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
#  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
#deploy:
#  provider: script
#  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
#  on:
#    branch: master
