sudo: required

language: python

services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t eloo/raspberrypi3-homeassistant-git .

script:
  - docker run -d eloo/raspberrypi3-homeassistant-git /bin/sh -c "hass --version"
